package com.roox.ecgpro.util

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import androidx.core.content.FileProvider
import com.roox.ecgpro.data.model.EcgRecord
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfReportGenerator {
    private val sdf = SimpleDateFormat("MMM dd, yyyy HH:mm", Locale.US)

    fun generateAndShare(context: Context, record: EcgRecord) {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val headerPaint = Paint().apply { color = Color.parseColor("#D32F2F"); style = Paint.Style.FILL }
        val titlePaint = Paint().apply { color = Color.WHITE; textSize = 24f; typeface = Typeface.DEFAULT_BOLD; isAntiAlias = true }
        val subtitlePaint = Paint().apply { color = Color.WHITE; textSize = 12f; isAntiAlias = true }
        val headingPaint = Paint().apply { color = Color.parseColor("#D32F2F"); textSize = 14f; typeface = Typeface.DEFAULT_BOLD; isAntiAlias = true }
        val bodyPaint = Paint().apply { color = Color.DKGRAY; textSize = 11f; isAntiAlias = true }
        val linePaint = Paint().apply { color = Color.parseColor("#E0E0E0"); strokeWidth = 1f }

        // Header
        canvas.drawRect(0f, 0f, 595f, 70f, headerPaint)
        canvas.drawText("🫀 ECG Pro Report", 20f, 35f, titlePaint)
        canvas.drawText("AI-Powered ECG Interpretation — Powered by Root 🌱", 20f, 55f, subtitlePaint)

        var y = 90f

        // Patient
        canvas.drawText("Patient Information", 20f, y, headingPaint); y += 20f
        canvas.drawText("Name: ${record.patientName.ifBlank { "N/A" }} | Age: ${record.patientAge.ifBlank { "N/A" }} | Gender: ${record.patientGender.ifBlank { "N/A" }}", 20f, y, bodyPaint); y += 16f
        if (record.symptoms.isNotBlank()) { canvas.drawText("Symptoms: ${record.symptoms}", 20f, y, bodyPaint); y += 16f }
        if (record.clinicalHistory.isNotBlank()) { canvas.drawText("History: ${record.clinicalHistory}", 20f, y, bodyPaint); y += 16f }
        canvas.drawText("Date: ${sdf.format(Date(record.timestamp))}", 20f, y, bodyPaint); y += 20f
        canvas.drawLine(20f, y, 575f, y, linePaint); y += 15f

        // Diagnosis
        canvas.drawText("Diagnosis", 20f, y, headingPaint); y += 20f
        canvas.drawText(record.diagnosis.take(90), 20f, y, bodyPaint); y += 16f
        if (record.confidence > 0) { canvas.drawText("Confidence: ${record.confidence}%", 20f, y, bodyPaint); y += 16f }
        canvas.drawText("Urgency: ${record.urgencyLevel.uppercase()}", 20f, y, bodyPaint); y += 16f
        if (record.acsRisk.isNotBlank()) { canvas.drawText("ACS Risk: ${record.acsRisk}", 20f, y, bodyPaint); y += 16f }
        if (record.lvefStatus.isNotBlank()) { canvas.drawText("LVEF: ${record.lvefStatus}", 20f, y, bodyPaint); y += 16f }
        y += 5f; canvas.drawLine(20f, y, 575f, y, linePaint); y += 15f

        // Measurements
        canvas.drawText("Measurements", 20f, y, headingPaint); y += 20f
        val measurements = listOf(
            "HR: ${record.heartRate} bpm", "Rhythm: ${record.rhythm}", "Axis: ${record.axis} (${record.axisClassification})",
            "PR: ${record.prInterval}", "QRS: ${record.qrsDuration}", "QT: ${record.qtInterval}",
            "Layout: ${record.ecgLayout}", "Speed: ${record.paperSpeed}mm/s", "Gain: ${record.voltageGain}mm/mV"
        )
        for (m in measurements) { if (m.contains(": 0") && !m.contains("mm")) continue; canvas.drawText(m, 20f, y, bodyPaint); y += 14f }
        y += 5f; canvas.drawLine(20f, y, 575f, y, linePaint); y += 15f

        // Full Analysis (truncated to fit)
        canvas.drawText("Analysis Summary", 20f, y, headingPaint); y += 20f
        val lines = record.fullAnalysis.take(1500).split("\n")
        for (line in lines) {
            if (y > 780f) break
            val trimmed = line.take(85)
            canvas.drawText(trimmed, 20f, y, bodyPaint); y += 13f
        }

        // Footer
        val disclaimerPaint = Paint().apply { color = Color.GRAY; textSize = 8f; isAntiAlias = true }
        canvas.drawText("⚠️ AI-assisted interpretation only. Always verify with a qualified cardiologist.", 20f, 825f, disclaimerPaint)
        canvas.drawText("Model: ${record.aiModel} | Generated by ECG Pro 🌱", 350f, 825f, disclaimerPaint)

        doc.finishPage(page)

        // Save
        val dir = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "ECG_Reports")
        dir.mkdirs()
        val file = File(dir, "ECG_Report_${record.id}_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()

        // Share
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share ECG Report"))
        Toast.makeText(context, "PDF saved: ${file.name}", Toast.LENGTH_LONG).show()
    }
}
